# .github/workflows/deploy.yml
name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This line was correctly indented

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true

    #   - name: Install Jekyll # This step is likely redundant if bundler-cache is true and jekyll is in Gemfile
    #     run: gem install jekyll bundler

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: Build CSS with npm script
        run: npm run start # Make sure 'npm run start' also triggers jekyll:build for gh-pages deployment

      # Uncomment if you want to run Jekyll build explicitly
      # - name: Build Jekyll site
      #   run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages